apt-get install python-mysqldb
pip install django
pip install django-ordered-listview
pip install django_dajax
pip install django-jquery
pip install django-contrib-comments
pip install django-registration
pip install django-tagging
pip install django-tagging-autocomplete
pip install markdown
easy_install -U django_evolution
