# -*- coding: utf-8 -*-

"""Ovo je hacky skripta za ubacivanje pocetnih zadatka u bazu.
Uporaba (ignorirati warninge):

cd ~/dora/
python manage.py shell
>>> import ubaci_zadatke
"""


from django.contrib.auth.models import User
from zadaci.models import Zadatak, Glas, Profil, Aktivnost

satja = User.objects.get(username='satja')

# Ubacit cemo i satjin profil u bazu.
try:
    satjin_profil = Profil(user=satja, ime='Adrian Satja',
                           prezime='Kurdija', spol='m', moto='lalala')
    satjin_profil.save()
except:
    print 'satjin profil, izgleda, vec je ubacen'

zadatci = [
    ['GTA',
     'http://hsin.hr/prip14/zadaci/prvi/zadaci.pdf',
     'Izborne pripreme 2014.',
     9,
     4,
     'ad-hoc flood-fill'],
    ['Bomboni',
     'http://hsin.hr/prip13/zadaci/prvi/zadaci.pdf',
     'Izborne pripreme 2013.',
     8,
     4,
     'ad-hoc bitmaske'],
    ['Poligoni',
     'http://hsin.hr/prip13/zadaci/prvi/zadaci.pdf',
     'Izborne pripreme 2013.',
     9,
     4,
     'dinamika'],
    ['Razgovori',
     'http://hsin.hr/prip13/zadaci/drugi/zadaci.pdf',
     'Izborne pripreme 2013.',
     9,
     4,
     'ad-hoc'],
    ['Buka',
     'http://hsin.hr/prip12/zadaci/prvi/zadaci.pdf',
     'Izborne pripreme 2012.',
     8,
     5,
     'interaktivni ad-hoc'],
    ['Autocesta',
     'http://hsin.hr/prip12/zadaci/drugi/zadaci.pdf',
     'Izborne pripreme 2012.',
     9,
     4,
     'dinamika sweep'],
    ['Multi',
     'http://hsin.hr/prip12/zadaci/drugi/zadaci.pdf',
     'Izborne pripreme 2012.',
     9,
     4,
     'dinamika kombinatorika'],
    ['Pekar',
     'http://hsin.hr/prip11/zadaci/prvi/zadaci.pdf',
     'Izborne pripreme 2011.',
     9,
     4,
     'divide-and-conquer ad-hoc'],
    ['Rotacije',
     'http://hsin.hr/hio2013/zadaci/zadaci.pdf',
     'Hrvatska informatička olimpijada - HIO 2013.',
     9,
     4,
     'ad-hoc rekurzija'],
    ['Snjeguljica',
     'http://hsin.hr/hio2013/zadaci/zadaci.pdf',
     'Hrvatska informatička olimpijada - HIO 2013.',
     7,
     4,
     'tournament'],
    ['Špijuni',
     'http://hsin.hr/hio2013/zadaci/zadaci.pdf',
     'Hrvatska informatička olimpijada - HIO 2013.',
     8,
     5,
     'grafovi minimum-spanning-tree'],
    ['Šetnja (HIO)',
     'http://hsin.hr/hio2012/zadaci/zadaci.pdf',
     'Hrvatska informatička olimpijada - HIO 2012.',
     8.5,
     5,
     'ad-hoc'],
    ['Trampolin',
     'http://hsin.hr/hio2012/zadaci/zadaci.pdf',
     'Hrvatska informatička olimpijada - HIO 2012.',
     7,
     5,
     'ad-hoc'],
    ['Rijeka',
     'http://hsin.hr/hio2011/zadaci/zadaci.pdf',
     'Hrvatska informatička olimpijada - HIO 2011.',
     6,
     4,
     'sweep'],
    ['Kule',
     'http://www.hsin.hr/dmih06/zadaci/pascal_c_cpp/dan1/prva/zadaci.pdf',
     'DMIH 2006., Srednjoškolska skupina, I. podskupina',
     7,
     4,
     'heuristika'],
    ['Stupovi',
     'http://www.hsin.hr/dmih07/zadaci/pascal_c_cpp/dan1/prva/zadaci.pdf',
     'DMIH 2007., Srednjoškolska skupina, I. podskupina',
     5,
     4,
     'stringovi greedy'],
    ['Guliver',
     'http://www.hsin.hr/dmih07/zadaci/pascal_c_cpp/dan1/prva/zadaci.pdf',
     'DMIH 2007., Srednjoškolska skupina, I. podskupina',
     7,
     5,
     'dijkstra 0-1-bfs'],
    ['Informacije',
     'http://www.hsin.hr/honi/arhiva/2012_2013/kolo2_zadaci.pdf',
     'HONI 2012/2013, 2. kolo',
     7,
     5,
     'matching'],
    ['Policija',
     'http://www.hsin.hr/dmih07/zadaci/pascal_c_cpp/hio/zadaci.pdf',
     'Hrvatska informatička olimpijada - HIO 2007.',
     9,
     4,
     'grafovi dfs-stablo'],
    ['Transform a Sequence',
     'spoj block',
     'Sphere online judge',
     8,
     3,
     'ad-hoc'],
    ['The Ball',
     'spoj ball',
     'Frane Kurtović',
     7,
     4,
     'strukture-podataka dinamika'],
    ['Colours A, B, C, D',
     'spoj abcd',
     'Sphere online judge',
     6,
     4,
     'ad-hoc'],
    ['Reverse the Sequence',
     'spoj revseq',
     'Sphere online judge',
     7,
     3,
     'ad-hoc'],
    ['Looks like Nim - but it is not',
     'spoj game2',
     'Sphere online judge',
     7,
     3,
     'ad-hoc igre'],
    ['Hierarchy',
     'spoj maketree',
     'satja',
     6,
     3,
     'topoloski-sort grafovi dag'],
    ['Charlie and the Chocolate Factory',
     'spoj charlie',
     'satja',
     9,
     4,
     'matrice gaussova-eliminacija'],
    ['Wordplay',
     'spoj word',
     'satja',
     7,
     5,
     'grafovi eulerov-put'],
    ['Alpine Skiing',
     'spoj skiing',
     'Frane Kurtović',
     8,
     4,
     'dinamika'],
    ['The Longest Chain of Domino Tiles',
     'spoj domino1',
     'satja',
     5,
     4,
     'ad-hoc'],
    ['Villages by the River',
     'spoj villages',
     'Izborne pripreme 2011. - Dodatno natjecanje za izbor juniorskog tima',
     6,
     5,
     'bitmaske ad-hoc'],
    ['How Many Plusses',
     'spoj plusevi',
     'Izborne pripreme 2011. - Dodatno natjecanje za izbor juniorskog tima',
     5,
     4,
     'ad-hoc'],
    ['Yet Another Fancy Game',
     'spoj game3',
     'Sphere online judge',
     7,
     3,
     'ad-hoc igre'],
    ['The Glazier',
     'spoj glass',
     'satja',
     7,
     3,
     'ad-hoc'],
    ['Eight Directions Crossword',
     'spoj eight',
     'satja',
     7,
     3,
     'dinamika stringovi'],
    ['Štef and Barica',
     'spoj walk1',
     'satja',
     7,
     3,
     'matematika kombinatorika'],
    ['The Glazier 2',
     'spoj glass2',
     'Sphere online judge',
     8,
     3,
     'ad-hoc'],
    ['Hotels Along the Croatian Coast',
     'spoj hotels',
     'satja',
     5,
     4,
     'binary-search'],
    ['Help the Airline Company',
     'spoj remove',
     'Sphere online judge',
     9,
     3,
     'ad-hoc'],
    ['Lights, Snakes and Cages',
     'spoj cages',
     'Infokup 2014., Državno natjecanje, 6. razred',
     7,
     4,
     'ad-hoc'],
    ['Pretty Functions',
     'spoj pretty',
     'satja',
     8,
     4,
     'permutacije dinamika'],
    ['Divide and Conquer',
     'spoj divcon',
     'Adrian Satja Kurdija i Filip Pavetic',
     8,
     4,
     'tournament strukture-podataka igre'],
    ['Islands and Hotel Chains',
     'spoj hchains',
     'Sphere online judge',
     8,
     5,
     'eulerov-put'],
    ['Jane and Tarzan',
     'spoj jane',
     'satja',
     7,
     5,
     'flood-fill'],
    ['Mlijeko',
     'https://www.infokup.hr/natjecanje/dobavi-dokument/661',
     'Infokup 2014., Školsko natjecanje, 5. razred',
     2,
     4,
     'osnovnoskolski if-then-else simulacija'],
    ['Gusari',
     'https://www.infokup.hr/natjecanje/dobavi-dokument/665',
     'Infokup 2014., Školsko natjecanje, 6. razred',
     1,
     4,
     'osnovnoskolski simulacija osnovne-operacije'],
    ['Cedeovi',
     'https://www.infokup.hr/natjecanje/dobavi-dokument/666',
     'Infokup 2014., Školsko natjecanje, 7. razred',
     3,
     4,
     'osnovnoskolski simulacija stringovi nizovi'],
    ['Ploča',
     'https://www.infokup.hr/natjecanje/dobavi-dokument/706',
     'Infokup 2014., Županijsko natjecanje, 5. razred',
     4,
     4,
     'osnovnoskolski if-then-else ad-hoc'],
    ['Liftovi',
     'https://www.infokup.hr/natjecanje/dobavi-dokument/708',
     'Infokup 2014., Županijsko natjecanje, 6. razred',
     4,
     4,
     'osnovnoskolski simulacija for-petlja'],
    ['Boje',
     'https://www.infokup.hr/natjecanje/dobavi-dokument/710',
     'Infokup 2014., Županijsko natjecanje, 7. razred',
     3,
     3,
     'osnovnoskolski ad-hoc'],
    ['Brodovi (Infokup)',
     'https://www.infokup.hr/natjecanje/dobavi-dokument/710',
     'Infokup 2014., Županijsko natjecanje, 7. razred',
     5,
     4,
     'osnovnoskolski matrice'],
    ['Obrisana',
     'https://www.infokup.hr/natjecanje/dobavi-dokument/794',
     'Infokup 2014., Državno natjecanje, 5. razred',
     3,
     4,
     'osnovnoskolski nizovi ad-hoc'],
    ['Znamenke',
     'https://www.infokup.hr/natjecanje/dobavi-dokument/794',
     'Infokup 2014., Državno natjecanje, 5. razred',
     4,
     4,
     'osnovnoskolski znamenke for-petlja'],
    ['Autobus',
     'https://www.infokup.hr/natjecanje/dobavi-dokument/796',
     'Infokup 2014., Državno natjecanje, 6. razred',
     5,
     4,
     'osnovnoskolski for-petlja ad-hoc'],
    ['ANK',
     'https://www.infokup.hr/natjecanje/dobavi-dokument/798',
     'Infokup 2014., Državno natjecanje, 7. razred',
     5,
     4,
     'osnovnoskolski ad-hoc nizovi'],
    ['Šetnja (Infokup)',
     'https://www.infokup.hr/natjecanje/dobavi-dokument/800',
     'Infokup 2014., Državno natjecanje, 8. razred',
     7,
     5,
     'nestandardni osnovnoskolski ad-hoc challenge'],
    ['Treasure',
     'http://ceoi2013.hsin.hr/tasks/tasks_day1.pdf',
     'CEOI 2013., Primosten, Hrvatska',
     8,
     4,
     'ad-hoc interaktivni'],
    ['Tram',
     'http://ceoi2013.hsin.hr/tasks/tasks_day1.pdf',
     'CEOI 2013., Primosten, Hrvatska',
     9,
     4,
     'strukture-podataka'],
    ['Board',
     'http://ceoi2013.hsin.hr/tasks/tasks_day2.pdf',
     'CEOI 2013., Primosten, Hrvatska',
     8,
     4,
     'ad-hoc'],
    ['Watering',
     'http://ceoi2013.hsin.hr/tasks/tasks_day2.pdf',
     'CEOI 2013., Primosten, Hrvatska',
     9,
     4,
     'ad-hoc output-only rekurzija'],
    ['Timsko',
     'h11-1',
     '',
     3,
     4,
     'ad-hoc while-petlja osnovnoskolski'],
    ['Parket',
     'h11-4',
     '',
     4,
     3,
     'ad-hoc osnovnoskolski'],
    ['Razine',
     'h11-6',
     '',
     4,
     4,
     'ad-hoc osnovnoskolski for-petlja'],
    ['Šećer',
     'h11-7',
     '',
     3,
     4,
     'ad-hoc osnovnoskolski'],
    ['Kolo',
     'h11-7',
     '',
     4,
     4,
     'ad-hoc osnovnoskolski nizovi'],
    ['Gitara',
     'h11-7',
     '',
     5,
     4,
     'strukture-podataka stack'],
    ['Ljutnja',
     'spoj c1ljutnj',
     'HONI 2010/2011, 1. kolo',
     6,
     4,
     'binary-search ad-hoc'],
    ['Kompići',
     'spoj kompici',
     'HONI 2011/2012, 2. kolo',
     6.5,
     5,
     'bitmaske ad-hoc'],
    ['Knjige',
     'spoj knjige',
     'HONI 2010/2011, 2. kolo',
     5,
     4,
     'ad-hoc nizovi'],
    ['Znanstvenik',
     'spoj znanstve',
     'HONI 2010/2011, 3. kolo',
     6,
     4,
     'hash stringovi matrice binary-search'],
    ['Diferencija',
     'spoj diferenc',
     'HONI 2010/2011, 3. kolo',
     7,
     4,
     'strukture-podataka stack'],
    ['Dugovi',
     'spoj dugovi',
     'HONI 2010/2011, 4. kolo',
     7,
     5,
     'grafovi ad-hoc'],
    ['Brodovi',
     'spoj brodovi',
     'HONI 2010/2011, 5. kolo',
     5,
     4,
     'ad-hoc for-petlja osnovnoskolski'],
    ['Snagatori',
     'h12-1',
     '',
     2,
     4,
     'if-then-else osnovnoskolski'],
    ['Jabuke',
     'h12-1',
     '',
     3,
     4,
     'osnovnoskolski ad-hoc for-petlja'],
    ['Matrix',
     'h12-1',
     '',
     5,
     4,
     'matrice'],
    ['Vlakić',
     'h12-2',
     '',
     2,
     4,
     'osnovnoskolski if-then-else'],
    ['Obrni',
     'h12-3',
     '',
     2,
     4,
     'if-then-else znamenke while-petlja osnovnoskolski'],
    ['Robot',
     'h12-3',
     '',
     6,
     4,
     'ad-hoc'],
    ['Kule',
     'h12-4',
     '',
     3,
     4,
     'if-then-else ad-hoc osnovnoskolski'],
    ['Kino',
     'h12-4',
     '',
     3,
     4,
     'stringovi ad-hoc osnovnoskolski'],
    ['Pahulje',
     'h12-5',
     '',
     1,
     4,
     'osnovnoskolski osnovne-operacije'],
    ['Eko',
     'h12-5',
     '',
     4,
     4,
     'binary-search'],
    ['DNA',
     'h12-5',
     '',
     5,
     4,
     'dinamika'],
    ['Jack',
     'h12-6',
     '',
     3,
     4,
     'nizovi osnovnoskolski'],
    ['Prozori',
     'h12-6',
     '',
     4,
     5,
     'osnovnoskolski ad-hoc matrice stringovi'],
    ['Razgovor',
     'h13-1',
     '',
     2,
     4,
     'if-then-else osnovnoskolski'],
    ['Dom',
     'h13-1',
     '',
     3,
     4,
     'osnovnoskolski stringovi'],
    ['Ljubomora',
     'h13-1',
     '',
     6,
     4,
     'binary-search'],
    ['Snaga',
     'h13-1',
     '',
     7,
     5,
     'matematika teorija-brojeva'],
    ['Mars',
     'h13-1',
     '',
     8,
     5,
     'dinamika'],
    ['Križaljka',
     'h13-2',
     '',
     4,
     4,
     'osnovnoskolski stringovi matrice'],
    ['Mnogokut',
     'h13-3',
     '',
     2.5,
     4,
     'osnovnoskolski if-then-else'],
    ['Šahovnica',
     'h13-3',
     '',
     3,
     4,
     'osnovnoskolski for-petlja matrice'],
    ['Poredak',
     'h13-3',
     '',
     4,
     4,
     'stringovi ad-hoc'],
    ['Malcolm',
     'h13-3',
     '',
     5,
     4,
     'sweep'],
    ['Aerodrom',
     'h13-3',
     '',
     6,
     4,
     'binary-search'],
    ['Herkabe',
     'h13-3',
     '',
     7,
     4,
     'rekurzija trie stringovi'],
    ['Procesor',
     'h13-3',
     '',
     8,
     4,
     'bitmaske ad-hoc'],
    ['Sela',
     'h13-4',
     '',
     1.5,
     4,
     'osnovnoskolski if-then-else'],
    ['Čokolada',
     'h13-4',
     '',
     3,
     4,
     'osnovnoskolski stringovi ad-hoc if-then-else'],
    ['Taksi',
     'h13-5',
     '',
     2,
     4,
     'osnovnoskolski if-then-else'],
    ['Ljestvica',
     'h13-5',
     '',
     3,
     4,
     'osnovnoskolski stringovi'],
    ['Arhipelag',
     'h13-5',
     '',
     4.5,
     4,
     'osnovnoskolski matrice'],
    ['Totem',
     'h13-5',
     '',
     7,
     4,
     'bfs rekonstrukcija'],
    ['Hipercijevi',
     'h13-5',
     '',
     6,
     4,
     'grafovi bfs'],
    ['Rotiraj',
     'h13-5',
     '',
     8,
     4,
     'ad-hoc'],
    ['Mnogomet',
     'h13-5',
     '',
     9,
     4,
     'matematika vjerojatnost dinamika'],
    ['Baka',
     'h13-6',
     '',
     3,
     4,
     'osnovnoskolski stringovi'],
    ['Sume',
     'h13-6',
     '',
     4,
     4,
     'ad-hoc matematika osnovnoskolski'],
    ['Burek',
     'h13-6',
     '',
     6,
     4,
     'sweep'],
    ['Obilazak',
     'i12-Prvo',
     '',
     8,
     4,
     'ad-hoc rekurzija'],
    ['Facebook',
     'i12-Prvo',
     '',
     5,
     4,
     'grafovi flood-fill bfs dfs'],
    ['Keramicar',
     'i12-Prvo',
     '',
     3,
     4,
     'osnovnoskolski matrice'],
    ['Vjetar',
     'i12-Prvo',
     '',
     4,
     4,
     'matrice osnovnoskolski'],
    ['Arhitekti',
     'i11-Prvo',
     '',
     7,
     4,
     'dinamika stepenice'],
    ['Vjerojatnost',
     'i11-Prvo',
     'p2',
     7,
     4,
     'kombinatorika vjerojatnost matematika dinamika'],
    ['Ugljikovodik',
     'i11-Prvo',
     '',
     4,
     4,
     'ad-hoc'],
    ['Otoci',
     'i11-Prvo',
     '',
     6,
     4,
     'grafovi bfs'],
    ['Matrice',
     'i11-Prvo',
     '',
     7,
     4,
     'dinamika'],
    ['Monoton',
     'i11-Trece',
     '',
     3,
     4,
     'osnovnoskolski for-petlja'],
    ['Palindrom',
     'i11-Trece',
     '',
     4,
     4,
     'stringovi osnovnoskolski ad-hoc'],
    ['Kugle',
     'i11-Cetvrto',
     'p2',
     4,
     4,
     'ad-hoc nizovi osnovnoskolski'],
    ['Mrav',
     'i11-Peto',
     'p2',
     7,
     4,
     'dinamika matematika vjerojatnost'],
    ['Pijuni',
     'i11-Peto',
     '',
     5,
     4,
     'matrice'],
    ['Koordinatni',
     'i11-Peto',
     '',
     7,
     4,
     'logaritamska strukture-podataka'],
    ['Utovar',
     'i11-Peto',
     '',
     2,
     4,
     'osnovnoskolski osnovne-operacije'],
    ['Gubitnik',
     'i11-Sesto',
     '',
     4,
     4,
     'osnovnoskolski stringovi'],
    ['Bicikl',
     'i11-Sesto',
     '',
     6,
     5,
     'grafovi flood-fill bfs dfs'],
    ['Pravilni',
     'i11-Sesto',
     'p2',
     5,
     4,
     'osnovnoskolski nizovi'],
    ['Operator',
     'i10-Sesto',
     '',
     5,
     4,
     'dinamika'],
    ['Pogodak',
     'i10-Sesto',
     '',
     4,
     4,
     'binary-search osnovnoskolski'],
    ['Pakiranje',
     'i10-Sesto',
     '',
     5,
     4,
     'osnovnoskolski ad-hoc'],
    ['Snake',
     'i10-Drugo',
     '',
     8,
     4,
     'dinamika'],
    ['Kutije',
     'i10-Drugo',
     '',
     3,
     4,
     'osnovnoskolski if-then-else'],
    ['Milan',
     'i10-Drugo',
     '',
     5,
     4,
     'osnovnoskolski ad-hoc nizovi'],
    ['Noga',
     'i10-Trece',
     '',
     6,
     5,
     'ad-hoc nizovi'],
    ['Kaliopa',
     'i10-Trece',
     '',
     5,
     4,
     'osnovnoskolski rekurzija stringovi'],
    ['Edit',
     'i10-Trece',
     '',
     7,
     4,
     'dinamika stringovi'],
    ['Dalmacija',
     'i10-Trece',
     '',
     6,
     4,
     'sweep'],
    ['Informatijada',
     'i10-Cevrto',
     '',
     6,
     4,
     'nizovi binary-search'],
    ['Show',
     'i10-Cevrto',
     '',
     2,
     4,
     'osnovnoskolski if-then-else'],
    ['Ljestve',
     'i10-Cevrto',
     '',
     5,
     4,
     'osnovnoskolski ad-hoc stringovi nizovi'],
    ['Mozgalica',
     'i10-Peto',
     '',
     4,
     4,
     'osnovnoskolski nizovi'],
    ['Stablo2',
     'i10-Peto',
     '',
     7,
     4,
     'grafovi'],
    ['DNK',
     'i10-Prvo',
     '',
     5,
     4,
     'dinamika'],
    ['Katapult',
     'i10-Prvo',
     '',
     6,
     4,
     'grafovi'],
    ['Tramvaj',
     'https://zatemas.zrs.hr/?app=evaluator&evlshw=solver&cd=Bo%C5%BEo%2F2009%2FPrvo+kolo%2FPascal-C+P1%2F&evlsolve=Tramvaj+%5BBT09K1%5D',
     'IBT 2009., 1. kolo',
     7,
     5,
     'grafovi floyd-warshall'],
]

for z in zadatci:
    if z[2] == 'Sphere online judge':
        z[2] += ' (Spoj)'

    if z[1].startswith('spoj'):
        z[1] = 'http://www.spoj.com/problems/' + z[1][5:].upper()

    if z[2].startswith('satja'):
        z[2] = 'Adrian Satja Kurdija'

    if z[1].startswith('i10'):
        z[2] = 'IBT 2010., ' + z[1][4:] + ' kolo'
        z[1] = 'https://zatemas.zrs.hr/?app=evaluator&evlshw=solver&cd=Božo%2F2010%2F' +\
            z[1][4:] + '+kolo%2FPascal-C+P1%2F&evlsolve=' + z[0]

    if z[1].startswith('i11'):
        podskupina = (z[2] or 'p1').upper()
        z[2] = 'IBT 2011., ' + z[1][4:] + ' kolo'
        z[1] = 'https://zatemas.zrs.hr/?app=evaluator&evlshw=solver&cd=Božo%2F2011%2F' +\
            z[1][4:] + '+kolo%2FPascal-C+' + podskupina + '%2F&evlsolve=' + z[0]

    if z[1].startswith('i12'):
        z[2] = 'IBT 2012., 1. kolo'
        z[1] = 'https://zatemas.zrs.hr/?app=evaluator&evlshw=solver&cd=Božo%2F2012%2FPrvo+kolo%2F&evlsolve=' +\
            z[0]

    if z[1].startswith('h11'):
        z[2] = 'HONI 2010/2011, ' + z[1][4] + '. kolo'
        z[1] = 'http://hsin.hr/honi/arhiva/2010_2011/kolo' +\
            z[1][4] + '_zadaci.pdf'

    if z[1].startswith('h12'):
        z[2] = 'HONI 2011/2012, ' + z[1][4] + '. kolo'
        z[1] = 'http://hsin.hr/honi/arhiva/2011_2012/kolo' +\
            z[1][4] + '_zadaci.pdf'

    if z[1].startswith('h13'):
        z[2] = 'HONI 2012/2013, ' + z[1][4] + '. kolo'
        z[1] = 'http://hsin.hr/honi/arhiva/2012_2013/kolo' +\
            z[1][4] + '_zadaci.pdf'

    print "Ubacujem zadatak:", z[0]
    zad = Zadatak(ime=z[0], link=z[1], izvor=z[2],
                  tezina=z[3], kvaliteta=z[4],
                  tezina_br_glasova=1, kvaliteta_br_glasova=1,
                  obiljezja=z[5].replace(' ', ', '),
                  dodao_id=satja.pk)
    try:
        obj = Zadatak.objects.get(ime=z[0])
        print "Zadatak vec postoji"
    except Zadatak.DoesNotExist:
        zad.save()
        aktivnost = Aktivnost(user=satja, zadatak=zad, tip_aktivnosti='dodao')
        aktivnost.save()
        glas = Glas(user=satja, zadatak=zad, tip_glasa='tezina',
                    vrijednost=zad.tezina)
        glas.save()
        glas = Glas(user=satja, zadatak=zad, tip_glasa='kvaliteta',
                    vrijednost=zad.kvaliteta)
        glas.save()
        print "Zadatak ubacen"
        # zad.rijesen_od.add(satja)
        # zad.save()
